USE TEMPDB
GO

CREATE TABLE MST_SUBPRODUCTTYPE
(

SUBPRODUCTTYPEID INT PRIMARY KEY Identity,
PRODUCTTYPEID INT  ,
SUBPRODUCTTYPENAME VARCHAR(50) NOT NULL
)

ALTER TABLE MST_SUBPRODUCTTYPE
ADD CONSTRAINT FK_MST_SUBPRODUCTTYPE_PRODUCT_TYPE_ID FOREIGN KEY (PRODUCTTYPEID)
REFERENCES MST_PRODUCTTYPE (PRODUCTTYPEID)

--DROP TABLE MST_SUBPRODUCTTYPE



