USE TEMPDB
GO

CREATE TABLE TRN_PRODUCT_DETAILS
(
PRODUCTID INT PRIMARY KEY Identity,
PRODUCTTYPEID INT  ,
SUBPRODUCTTYPEID INT ,
PRODUCTNAME VARCHAR(20),
PRODUCTDESC VARCHAR(200),
PRODUCTQUANTITY NUMERIC,
PRODUCTVALUE NUMERIC,
PRODUCTOFFERS VARCHAR(100)
)
--Drop table TRN_PRODUCT_DETAILS


ALTER TABLE TRN_PRODUCT_DETAILS
ADD CONSTRAINT FK_TRN_PRODUCT_DETAILS_PRODUCT_TYPE_ID FOREIGN KEY (PRODUCTTYPEID)
REFERENCES MST_PRODUCTTYPE (PRODUCTTYPEID)

ALTER TABLE TRN_PRODUCT_DETAILS
ADD CONSTRAINT FK_TRN_PRODUCT_DETAILS_SUBPRODUCT_TYPE_ID FOREIGN KEY (SUBPRODUCTTYPEID)
REFERENCES MST_SUBPRODUCTTYPE (SUBPRODUCTTYPEID)


--Drop Table TRN_PRODUCT_DETAILS



