USE TEMPDB
GO
--ISP_PRODUCT_TYPE 'Home Decor'
CREATE PROCEDURE ISP_PRODUCT_TYPE
@PRODUCTNAME AS VARCHAR(50)
AS 
BEGIN
	BEGIN TRY
		INSERT INTO MST_PRODUCTTYPE VALUES (@PRODUCTNAME)
		SELECT 1 AS RESULT
	END TRY
	BEGIN CATCH
		SELECT 0 AS RESULT
	END CATCH
END

