USE TEMPDB
GO

CREATE PROCEDURE RSP_PRODUCT_TYPE  
@PRODUCTTYPEID AS VARCHAR(10)
AS   
BEGIN  
 BEGIN TRY  
DELETE FROM MST_PRODUCTTYPE WHERE PRODUCTTYPEID =@PRODUCTTYPEID
 SELECT 1 AS RESULT
 END TRY  
 BEGIN CATCH  
  SELECT 0 AS RESULT
 END CATCH  
END  
   