USE TEMPDB
GO

CREATE PROCEDURE USP_PRODUCT_TYPE  
@PRODUCTTYPEID AS VARCHAR(10),
@PRODUCTTYPENAME AS VARCHAR(100)  
AS   
BEGIN  
 BEGIN TRY  
 UPDATE MST_PRODUCTTYPE
 SET PRODUCTTYPENAME = @PRODUCTTYPENAME
 WHERE PRODUCTTYPEID = @PRODUCTTYPEID

 SELECT 1 AS RESULT
 END TRY  
 BEGIN CATCH  
  SELECT 0 AS RESULT
 END CATCH  
END  
  