USE TEMPDB
GO
--CSP_PRODUCT_DETAILS 'Redmi'
Create PROCEDURE CSP_PRODUCT_DETAILS  
@PRODUCTNAME AS VARCHAR(100)=''  
AS   
BEGIN  
SET NOCOUNT OFF
 BEGIN TRY  
 IF ISNULL(@PRODUCTNAME ,'') = ''
 BEGIN
  SELECT COUNT(1) AS RESULT FROM TRN_PRODUCT_DETAILS   
  END
 ELSE
 BEGIN 
 DECLARE @STRSQL AS VARCHAR(500)
 SET   @STRSQL ='SELECT COUNT(1) AS RESULT FROM TRN_PRODUCT_DETAILS
	   WHERE PRODUCTNAME LIKE ''%'+ @PRODUCTNAME  +'%'''
	   EXEC (@STRSQL)
 END
 END TRY  
 BEGIN CATCH  
  SELECT 0 AS PRODUCT_TYPE_ID  , 'ERROR OCCURED' AS OUTPUT2    
 END CATCH  
END  
  