USE TEMPDB
GO
--DSP_PRODUCT_DETAILS 'Redmi',2,5
ALTER PROCEDURE DSP_PRODUCT_DETAILS  
@PRODUCTNAME AS VARCHAR(10)=''  ,
@PageNumber INT, 
@PageSize   INT
AS   
BEGIN  
 BEGIN TRY  
 IF ISNull(@PRODUCTNAME,'') =''  
 BEGIN
 WITH ctepaging 
     AS (SELECT PRODUCTID,PRODUCTTYPEID,SUBPRODUCTTYPEID,PRODUCTNAME,PRODUCTDESC,PRODUCTQUANTITY,PRODUCTVALUE,PRODUCTOFFERS,
                Row_number() OVER(ORDER BY PRODUCTID,PRODUCTTYPEID,SUBPRODUCTTYPEID,PRODUCTNAME,PRODUCTDESC,PRODUCTQUANTITY,PRODUCTVALUE,PRODUCTOFFERS) AS rownum 
         FROM TRN_PRODUCT_DETAILS) 
SELECT * 
FROM   ctepaging 
WHERE  rownum BETWEEN ( @PageNumber - 1 ) * @PageSize + 1 AND
@PageNumber * @PageSize

  END
 ELSE
 BEGIN
 Declare @strSQL as Varchar(500)
 SET   @strSQL = 'WITH ctepaging 
     AS (SELECT PRODUCTID,PRODUCTTYPEID,SUBPRODUCTTYPEID,PRODUCTNAME,PRODUCTDESC,PRODUCTQUANTITY,PRODUCTVALUE,PRODUCTOFFERS,
                Row_number() OVER(ORDER BY PRODUCTID,PRODUCTTYPEID,SUBPRODUCTTYPEID,PRODUCTNAME,PRODUCTDESC,PRODUCTQUANTITY,PRODUCTVALUE,PRODUCTOFFERS) AS rownum 
         FROM TRN_PRODUCT_DETAILS WHERE PRODUCTNAME like ''%'+ @PRODUCTNAME + '%'') 
SELECT * 
FROM   ctepaging 
WHERE  rownum BETWEEN ( '+Convert(Varchar(10),@PageNumber)+' - 1 ) * '+Convert(Varchar(10),@PageSize)+' + 1 AND
'+Convert(Varchar(10),@PageNumber)+' * '+Convert(Varchar(10),@PageSize) 

 EXEC(@strSQL) 

  END
 END TRY  
 BEGIN CATCH  
 Select ERROR_MESSAGE()
  SELECT 0 AS PRODUCT_TYPE_ID  , 'ERROR OCCURED' AS OUTPUT2    
 END CATCH  
END  
  