USE TEMPDB
GO
--ISP_PRODUCT_DETAILS 1,1,'Toys','',50,5611,''
Create PROCEDURE ISP_PRODUCT_DETAILS
@PRODUCTTYPEID	as int,
@SUBPRODUCTTYPEID as int,
@PRODUCTNAME as varchar(50),
@PRODUCTDESC as varchar(200),
@PRODUCTQUANTITY as numeric,
@PRODUCTVALUE as numeric,
@PRODUCTOFFERS as varchar(100)
AS 
BEGIN
	BEGIN TRY
		INSERT INTO TRN_PRODUCT_DETAILS (PRODUCTTYPEID,SUBPRODUCTTYPEID,PRODUCTNAME,PRODUCTDESC,PRODUCTQUANTITY,PRODUCTVALUE,PRODUCTOFFERS) VALUES 
		(@PRODUCTTYPEID,@SUBPRODUCTTYPEID,@PRODUCTNAME,@PRODUCTDESC,@PRODUCTQUANTITY,@PRODUCTVALUE,@PRODUCTOFFERS)
		SELECT 1 AS RESULT
	END TRY
	BEGIN CATCH
		SELECT 0 AS RESULT
	END CATCH
END

