USE TEMPDB
GO

CREATE PROCEDURE RSP_PRODUCT_DETAILS  
@PRODUCTID AS VARCHAR(10)
AS   
BEGIN  
 BEGIN TRY  
Delete From TRN_PRODUCT_DETAILS where PRODUCTID =@PRODUCTID
 SELECT 1 AS RESULT
 END TRY  
 BEGIN CATCH  
  SELECT 0 AS RESULT
 END CATCH  
END  
   