USE TEMPDB
GO

CREATE PROCEDURE USP_PRODUCT_DETAILS  
@PRODUCTID as int,
@PRODUCTTYPEID	as int,
@SUBPRODUCTTYPEID as int,
@PRODUCTNAME as varchar(50),
@PRODUCTDESC as varchar(200),
@PRODUCTQUANTITY as numeric,
@PRODUCTVALUE as numeric,
@PRODUCTOFFERS as varchar(100)
AS   
BEGIN  
 BEGIN TRY  
 UPDATE TRN_PRODUCT_DETAILS
 SET PRODUCTTYPEID	=@PRODUCTTYPEID,
SUBPRODUCTTYPEID =@SUBPRODUCTTYPEID,
PRODUCTNAME =@PRODUCTNAME,
PRODUCTDESC =@PRODUCTDESC,
PRODUCTQUANTITY =@PRODUCTQUANTITY,
PRODUCTVALUE =@PRODUCTVALUE,
PRODUCTOFFERS =@PRODUCTOFFERS
 WHERE @PRODUCTID = @PRODUCTID

 SELECT 1 AS RESULT
 END TRY  
 BEGIN CATCH  
  SELECT 0 AS RESULT
 END CATCH  
END  
  