USE TEMPDB
GO

CREATE PROCEDURE DSP_SUBPRODUCT_TYPE  
@SUBPRODUCTTYPEID AS VARCHAR(50)=NULL  
AS   
BEGIN  
 BEGIN TRY  
 IF @SUBPRODUCTTYPEID IS NULL  
  SELECT SUBPRODUCTTYPEID  ,PRODUCTTYPEID  , SUBPRODUCTTYPENAME FROM MST_SUBPRODUCTTYPE   
 ELSE  
  SELECT SUBPRODUCTTYPEID  ,PRODUCTTYPEID  , SUBPRODUCTTYPENAME FROM MST_SUBPRODUCTTYPE    WHERE SUBPRODUCTTYPEID = @SUBPRODUCTTYPEID  
  
 END TRY  
 BEGIN CATCH  
  SELECT 0 AS PRODUCT_TYPE_ID  , 'ERROR OCCURED' AS OUTPUT2  ,'Something Went Wrong' AS OUTPUT2  
 END CATCH  
END  
  