USE TEMPDB
GO
Create PROCEDURE ISP_SUBPRODUCT_TYPE
@PRODUCTYPEID AS int,
@SUBPRODUCTYPENAME AS Varchar(50)
AS 
BEGIN
	BEGIN TRY
		INSERT INTO MST_SUBPRODUCTTYPE (PRODUCTTYPEID,SUBPRODUCTTYPENAME) VALUES (@PRODUCTYPEID,@SUBPRODUCTYPENAME)
		SELECT 1 AS RESULT
	END TRY
	BEGIN CATCH
		SELECT 0 AS RESULT
	END CATCH
END

