--RSP_SUBPRODUCT_TYPE 5  
CREATE PROCEDURE RSP_SUBPRODUCT_TYPE    
@SUBPRODUCTTYPEID AS VARCHAR(10)  
AS     
BEGIN    
 BEGIN TRY    
Delete From MST_SUBPRODUCTTYPE where SUBPRODUCTTYPEID =@SUBPRODUCTTYPEID  
 SELECT 1 AS RESULT  
 END TRY    
 BEGIN CATCH    
  SELECT 0 AS RESULT  
 END CATCH    
END    