USE TEMPDB
GO

CREATE PROCEDURE USP_SUBPRODUCT_TYPE    
@SUBPRODUCTTYPEID AS VARCHAR(10),  
@PRODUCTTYPEID AS VARCHAR(10),  
@SUBPRODUCTTYPENAME AS VARCHAR(100)    
AS     
BEGIN    
 BEGIN TRY    
 UPDATE MST_SUBPRODUCTTYPE  
 SET SUBPRODUCTTYPENAME = @SUBPRODUCTTYPENAME,  
 PRODUCTTYPEID = @PRODUCTTYPEID  
 WHERE SUBPRODUCTTYPEID = @SUBPRODUCTTYPEID  
  
 SELECT 1 AS RESULT  
 END TRY    
 BEGIN CATCH    
 Select ERROR_MESSAGE()  
  SELECT 0 AS RESULT  
 END CATCH    
END    
END  
  